export const bankCardImage: Record<string, string> = {
  '062': '/bank-cards/ayande.svg',
  // '002': '/bank-cards/bankino.svg',
  // '003': '/bank-cards/blue.svg',
  '066': '/bank-cards/dey.svg',
  '055': '/bank-cards/eghtesad.svg',
  '064': '/bank-cards/gardeshgari.svg',
  '069': '/bank-cards/iranzamin.svg',
  '016': '/bank-cards/keshavarzi.svg',
  '078': '/bank-cards/khavarmianeh.svg',
  '014': '/bank-cards/maskan.svg',
  '060': '/bank-cards/mehr.svg',
  '012': '/bank-cards/mellat.svg',
  '017': '/bank-cards/melli.svg',
  '054': '/bank-cards/parsian.svg',
  '057': '/bank-cards/pasargad.svg',
  '018': '/bank-cards/tejarat.svg',
  '021': '/bank-cards/post.svg',
  '013': '/bank-cards/refah.svg',
  '019': '/bank-cards/saderat.svg',
  '056': '/bank-cards/saman.svg',
  '011': '/bank-cards/sanatmadan.svg',
  '010': '/bank-cards/sarmaye.svg',
  '015': '/bank-cards/sepah.svg',
  '061': '/bank-cards/shahr.svg',
  '070': '/bank-cards/sina.svg',
  '022': '/bank-cards/tosee.svg',
}