import type { Metadata } from 'next'
import './assets/globals.css'
import { StatesProvider } from '@/context/States'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <StatesProvider>
      <html lang='en'>
        <body
          suppressHydrationWarning={true}
          className='flex flex-col items-center'
        >
          <div className='max-w-[11 20px] w-full px-4'>{children}</div>
        </body>
      </html>
    </StatesProvider>
  )
}
