import type { Metadata } from 'next'
import './assets/globals.css'
import { StatesProvider } from '@/context/States'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <StatesProvider>
      <html lang='en'>
        <body>{children}</body>
      </html>
    </StatesProvider>
  )
}
